### ISSUE TITLE
svg-url function not working on IE

### ISSUE THREAD

**Issue by pierreburel** [sindresorhus/sass-extras#1]
The SVG encoded with `svg-url` aren't compatibles with IE10+ (yeah, i know it's a pretty old browser, but heh…).

I think it could come from the quotes used to wrap the encoded `data` (which need to be double) and thus the ones for the attributes (which need to be single and not encoded), see [this article](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris#its-all-in-the-quotes-1). And I guess `<` and `>` need to be encoded to.

Would it be ok to alter the `url-encode` to change the encoding for maximizing the compatibility, or maybe create a specific `encode-svg` to keep the first one clean ? Or maybe you just don't want to support IE ? I would be happy to suggest a PR if you want.

**Comment by sindresorhus** [comment]
Sorry, but I'm only targeting the latest browsers here. Forgot to mention that in the readme. Done now: https://github.com/sindresorhus/sass-extras/blob/master/readme.md#supported-browsers
