### ISSUE TITLE
Public site is down

### ISSUE THREAD

**Issue by edelstone** [sindresorhus/sass-extras#4]
Hey there,

The [Sass Extras public site](https://sindresorhus.com/sass-extras) has been down for a little while. It currently shows a browser error page. Have you stopped supporting the site?

Best,
Michael

<img width="1568" alt="Screenshot 2022-11-25 at 8 50 29 AM 1" src="https://user-images.githubusercontent.com/8269046/204009840-8edb03f8-f61d-4eec-93e3-d059bec1d6d6.png">

**Comment by sindresorhus** [comment]
It's back: https://sindresorhus.com/sass-extras/
